news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB,GiornalistaListView

app_name="news"

urlpatterns=[  
    path('', home, name ="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti")
]

prima_app/urls.py
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index
app_name = 'prima_app'
urlpatterns = [

    path('welcome/', homepage, name='homepage'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('prima_app/', include('prima_app.urls')),
    path('seconda_app/', include('seconda_app.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('forms_app/', include('forms_app.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

seconda_app/urls.py
from django.urls import path
from .views import es_if,es_ifelse, es_elif, esfor
app_name = 'seconda_app'
urlpatterns = [
    path('if', es_if, name='if'),
    path('ifelse', es_ifelse, name='ifelse'),
    path('ifelif', es_elif, name='elif'),
    path('for', esfor, name='for'),
]

prima_app/models.py
from django.db import models

# Create your models here.

prima_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.

#L1
def homepage(request):
    return render(request, "homepage.html")

#L2
def menu(request):
    return HttpResponse("<ol><li>Prima opzione</li><li>Seconda opzione</li><li>Terza opzione</li></ol>")

#L3
def chisiamo(request):
    return render(request, "chi_siamo.html")
#L4
def variabili(request):
    context= { 'var1': '10','var2': 'ciao', 'var3' : '123 hello world'}
    return render(request, "variabili.html",context)
#L5
def index(request):
    return render(request, "index.html")

prima_app/templates/chi_siamo.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Index
{%endblock title%}

{%block content%}
<title>Chi siamo</title>
    <h3>Siamo quelli che siamo ?</h3>
{%endblock content%}

prima_app/templates/homepage.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

    <h3>Ciao a tutti e benvenuti nella homepage!</h3>

    <h3>Prima app:</h3>
    <ol>
        <li><a href="{% url 'prima_app:index'%}">index</a></li>
        <li><a href="{% url 'prima_app:homepage'%}">welcome</a></li>
        <li><a href="{% url 'prima_app:menu'%}">menu</a></li>
        <li><a href="{% url 'prima_app:chisiamo'%}">chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">variabili</a></li>
    </ol>

    <h3>Seconda app:</h3>
     <ol>
        <li><a href="{% url 'prima_app:esfor'%}">esercizio for</a></li>
        <li><a href="{% url 'prima_app:es_if'%}">esercizio if</a></li>
        <li><a href="{% url 'prima_app:es_elif'%}">esercizio ifelif</a></li>
        <li><a href="{% url 'prima_app:es_ifelse'%}">esercizio ifelse</a></li>
    </ol>

</body>
</html>

prima_app/templates/index.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Index
{%endblock title%}

{%block content%}
    <h3>Ciao a tutti e benvenuti nella homepage!</h3>

    <h3>Prima app:</h3>
    <ol>
        <li><a href="{% url 'prima_app:index'%}">index</a></li>
        <li><a href="{% url 'prima_app:menu'%}">menu</a></li>
        <li><a href="{% url 'prima_app:chisiamo'%}">chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">variabili</a></li>
    </ol>

    <h3>Seconda app:</h3>
     <ol>
        <li><a href="{% url 'seconda_app:for'%}">esercizio for</a></li>
        <li><a href="{% url 'seconda_app:if'%}">esercizio if</a></li>
        <li><a href="{% url 'seconda_app:elif'%}">esercizio ifelif</a></li>
        <li><a href="{% url 'seconda_app:ifelse'%}">esercizio ifelse</a></li>
    </ol>
{%endblock content%}

prima_app/templates/variabili.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Index
{%endblock title%}

{%block content%}
<title> Variabili </title>
<ol>
    <li> {{ var1 }}</li>
    <li> {{ var2 }}</li>
    <li> {{ var3 }}</li>
</ol>
{%endblock content%}